version: '3.8'
services:
 nodejs:
  container_name: express
  build: 
   context: .
   dockerfile: Dockerfile 
  ports: 
   - 4000:4000
  volumes:
   - ./src/:/APP/src/ 
  enviroment:
   - NODE_MODULE=PROD
   - PORT=4000

