version: '3.8'
services:
 nodejs:
  build:
    context: .
    dockerfile: Dockerfile
    target: production 
    # args:
    #  - NODE_ENV=PRODUCTION
  environment:
    - NODE_MODULE=PROD
  command: npm start